version: "3.9"
services:
  budget-app:
    build:
      context: .
      dockerfile: ./docker/budget/Dockerfile
    image: klwxsrx/budget-tracker
    container_name: budget-app
    hostname: budget-app
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      MESSAGE_BROKER_ADDRESS: "budget-pulsar:6650"
      DATABASE_NAME: budget
      DATABASE_ADDRESS: "budget-mysql:3306"
      DATABASE_USER: budget
      DATABASE_PASSWORD: 1234
    depends_on:
      - budget-mysql
      - budget-pulsar
  budget-view-app:
    build:
      context: .
      dockerfile: ./docker/budget-view/Dockerfile
    image: klwxsrx/budget-tracker-view
    container_name: budget-view-app
    hostname: budget-view-app
    ports:
      - "127.0.0.1:8081:8080"
    environment:
      MESSAGE_BROKER_ADDRESS: "budget-pulsar:6650"
      DATABASE_ADDRESS: "budget-mongo:27017"
      DATABASE_USER: budget-view
      DATABASE_PASSWORD: 1234
    depends_on:
      - budget-mongo
      - budget-pulsar
  budget-mysql:
    image: mysql:8.0
    container_name: budget-mysql
    hostname: budget-mysql
    volumes:
      - budget-mysql-data:/var/lib/mysql:rw
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: budget
      MYSQL_USER: budget
      MYSQL_PASSWORD: 1234
    healthcheck:
      test: mysql -h127.0.0.1 -ubudget -p1234 -e 'SELECT 1'
      interval: 10s
      timeout: 1s
  budget-mongo:
    image: mongo:4.4
    container_name: budget-mongo
    hostname: budget-mongo
    volumes:
      - budget-mongo-data:/data/db:rw
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGO_INITDB_DATABASE: budget-view
      MONGO_INITDB_ROOT_USERNAME: budget-view
      MONGO_INITDB_ROOT_PASSWORD: 1234
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo 127.0.0.1:27017/budget-view --quiet
      interval: 10s
      timeout: 1s
  budget-pulsar:
    image: apachepulsar/pulsar:2.7.0
    container_name: budget-pulsar
    hostname: budget-pulsar
    volumes:
      - budget-pulsar-data:/pulsar/data:rw
    ports:
      - "127.0.0.1:6650:6650"
    entrypoint: [ "bin/pulsar", "standalone" ]
volumes:
  budget-mysql-data:
  budget-mongo-data:
  budget-pulsar-data: