version: "3.9"
services:
  budget-app:
    image: klwxsrx/budget-tracker:master
    container_name: budget-app
    hostname: budget-app
    environment:
      MESSAGE_BROKER_ADDRESS: "budget-pulsar:6650"
      MESSAGE_BROKER_CONNECTION_TIMEOUT: 600 # connection may be too slow for the first time due to initialization
      DATABASE_ADDRESS: "budget-mysql:3306"
      DATABASE_NAME: budget
      DATABASE_USER: budget
      DATABASE_PASSWORD: 1234
      DATABASE_CONNECTION_TIMEOUT: 300
    depends_on:
      - budget-mysql
      - budget-pulsar
    ports:
      - "127.0.0.1:8080:8080"
  budget-view-app:
    image: klwxsrx/budget-tracker-view:master
    container_name: budget-view-app
    hostname: budget-view-app
    environment:
      MESSAGE_BROKER_ADDRESS: "budget-pulsar:6650"
      MESSAGE_BROKER_CONNECTION_TIMEOUT: 600
      DATABASE_ADDRESS: "budget-view-mysql:3306"
      DATABASE_NAME: budget_view
      DATABASE_USER: budget_view
      DATABASE_PASSWORD: 1234
      DATABASE_CONNECTION_TIMEOUT: 300
      REALTIME_ADDRESS: "budget-centrifugo:8000"
      REALTIME_API_KEY: 07ceb863-0ae1-4d5f-a2de-fba2d2e6058b
    depends_on:
      - budget-view-mysql
      - budget-pulsar
    ports:
      - "127.0.0.1:8081:8080"
  budget-mysql:
    image: mysql:8.0
    container_name: budget-mysql
    hostname: budget-mysql
    volumes:
      - budget-mysql-data:/var/lib/mysql:rw
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: budget
      MYSQL_USER: budget
      MYSQL_PASSWORD: 1234
    healthcheck:
      test: mysql -h127.0.0.1 -ubudget -p1234 -e 'SELECT 1'
      interval: 10s
      timeout: 1s
  budget-view-mysql:
    image: mysql:8.0
    container_name: budget-view-mysql
    hostname: budget-view-mysql
    volumes:
      - budget-view-mysql-data:/var/lib/mysql:rw
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: budget_view
      MYSQL_USER: budget_view
      MYSQL_PASSWORD: 1234
    healthcheck:
      test: mysql -h127.0.0.1 -ubudget_view -p1234 -e 'SELECT 1'
      interval: 10s
      timeout: 1s
  budget-pulsar:
    image: apachepulsar/pulsar:2.9.1
    container_name: budget-pulsar
    hostname: budget-pulsar
    volumes:
      - budget-pulsar-data:/pulsar/data:rw
      - ./config/pulsar/standalone.conf:/pulsar/conf/standalone.conf:ro
    entrypoint: [ "bin/pulsar", "standalone" ]
    restart: unless-stopped
    healthcheck:
      test: /pulsar/bin/pulsar-admin brokers healthcheck
      interval: 30s
      timeout: 5s
      retries: 20
  budget-centrifugo:
    image: centrifugo/centrifugo:v3
    container_name: budget-centrifugo
    command: centrifugo --health
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    environment:
      CENTRIFUGO_TOKEN_HMAC_SECRET_KEY: 3a6e2259-0fd9-41cc-91f2-565874952c6a
      CENTRIFUGO_API_KEY: 07ceb863-0ae1-4d5f-a2de-fba2d2e6058b
      CENTRIFUGO_ALLOWED_ORIGINS: "*" # TODO: use specific origin
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:8000/health || exit 1
      interval: 10s
      timeout: 1s

volumes:
  budget-mysql-data:
  budget-view-mysql-data:
  budget-pulsar-data: