version: "3.9"
services:
  budget-app:
    build:
      context: .
      dockerfile: ./docker/budget/Dockerfile
    image: klwxsrx/budget-tracker
    container_name: budget-app
    hostname: budget-app
    environment:
      MESSAGE_BROKER_ADDRESS: "budget-pulsar:6650"
      MESSAGE_BROKER_CONNECTION_TIMEOUT: 300 # connection may be too slow for the first time due to initialization
      DATABASE_ADDRESS: "budget-mysql:3306"
      DATABASE_NAME: budget
      DATABASE_USER: budget
      DATABASE_PASSWORD: 1234
      DATABASE_CONNECTION_TIMEOUT: 300
    depends_on:
      - budget-mysql
      - budget-pulsar
  budget-view-app:
    build:
      context: .
      dockerfile: ./docker/budgetview/Dockerfile
    image: klwxsrx/budget-tracker-view
    container_name: budget-view-app
    hostname: budget-view-app
    environment:
      MESSAGE_BROKER_ADDRESS: "budget-pulsar:6650"
      MESSAGE_BROKER_CONNECTION_TIMEOUT: 300
      DATABASE_ADDRESS: "budget-view-mysql:3306"
      DATABASE_NAME: budget_view
      DATABASE_USER: budget_view
      DATABASE_PASSWORD: 1234
      DATABASE_CONNECTION_TIMEOUT: 300
    depends_on:
      - budget-view-mysql
      - budget-pulsar
  budget-mysql:
    image: mysql:8.0
    container_name: budget-mysql
    hostname: budget-mysql
    volumes:
      - budget-mysql-data:/var/lib/mysql:rw
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: budget
      MYSQL_USER: budget
      MYSQL_PASSWORD: 1234
    healthcheck:
      test: mysql -h127.0.0.1 -ubudget -p1234 -e 'SELECT 1'
      interval: 10s
      timeout: 1s
  budget-view-mysql:
    image: mysql:8.0
    container_name: budget-view-mysql
    hostname: budget-view-mysql
    volumes:
      - budget-view-mysql-data:/var/lib/mysql:rw
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: budget_view
      MYSQL_USER: budget_view
      MYSQL_PASSWORD: 1234
    healthcheck:
      test: mysql -h127.0.0.1 -ubudget_view -p1234 -e 'SELECT 1'
      interval: 10s
      timeout: 1s
  budget-pulsar:
    image: apachepulsar/pulsar:2.9.1
    container_name: budget-pulsar
    hostname: budget-pulsar
    volumes:
      - budget-pulsar-data:/pulsar/data:rw
    entrypoint: [ "bin/pulsar", "standalone" ]
    restart: unless-stopped
volumes:
  budget-mysql-data:
  budget-view-mysql-data:
  budget-pulsar-data: