version: "3.8"
services:
  expense:
    build:
      context: ../../
      dockerfile: ./deployments/expense/Dockerfile
    image: klwxsrx/expense-app
    container_name: expense-app
    hostname: expense-app
    depends_on:
      - expense-db
  expense-db:
    image: mysql:8.0
    container_name: expense-db
    hostname: expense-db
    volumes:
      - expense-db-data:/var/lib/mysql:rw
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: expense
      MYSQL_USER: expense
      MYSQL_PASSWORD: 1234
volumes:
  expense-db-data: