version: "3.8"
services:
  expense:
    build:
      context: ../
      dockerfile: ./docker/expense/Dockerfile
    image: klwxsrx/expense-app
    container_name: expense-app
    hostname: expense-app
    ports:
      - 8080:8080
    environment:
      DATABASE_NAME: expense
      DATABASE_ADDRESS: "expense-db:3306"
      DATABASE_USER: expense
      DATABASE_PASSWORD: 1234
      DATABASE_MAX_CONNECTIONS: 10
    depends_on:
      - expense-db
  expense-db:
    image: mysql:8.0
    container_name: expense-db
    hostname: expense-db
    volumes:
      - expense-db-data:/var/lib/mysql:rw
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: expense
      MYSQL_USER: expense
      MYSQL_PASSWORD: 1234
volumes:
  expense-db-data: